apiVersion: v1
kind: ConfigMap
metadata:
  name: ctasd
data:
  ctasd.conf: |
    [General]
    PersistentCacheEnabled=0
    ValidBulkEnabled=1
    SpamdServerEnabled=0
    AsyncResolverRequests=0

    [Connectivity]
    License_key_code=xxxxxxxxxxxxxxxxxxxx
    Server_address=Resolver%d.halon.ctmail.com
    Additional=WebSecZeroLatencyMode=0;UseLibcurl=0;AsyncThreads=0;HttpConnPoolSize=50;Hash=65533;
    Cache_max_records=100000

    [Security]
    User=ctasd
    Group=ctasd

    [HttpServer]
    Port=8088
    ListenBackLog=100
    InitialThreads=25
    MaxThreads=50
    Concurrency=50
    TempFolder=/tmp/ctasd/

    [Spamd]

    [AV]

    [Stats]

    [Outbound]

    [LocalView]
    LocalView_BulkThreshold=5
    LocalView_ConfirmedThreshold=10
---
apiVersion: v1
kind: Service
metadata:
  name: ctasd
  labels:
    app: ctasd
spec:
  ports:
  - port: 8088
    name: socket
  selector:
    app: ctasd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctasd
  labels:
    app: ctasd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctasd
  template:
    metadata:
      labels:
        app: ctasd
    spec:
      containers:
      - name: ctasd
        image: ctasd:5.01.0008.1
        ports:
        - containerPort: 8088
          name: socket
        readinessProbe:
          tcpSocket:
            port: 8088
        livenessProbe:
          tcpSocket:
            port: 8088
        volumeMounts:
        - mountPath: /etc/ctasd
          name: config
      volumes:
      - name: config
        configMap:
          name: ctasd